pipeline {
    agent { 
        dockerfile {
            filename 'Dockerfile'
            dir 'jenkins'
        } 
    }
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
            }
        }
    }
}