pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo "build"
            }
        }

        stage('Deploy') {
            steps {
                sh "echo 'Hello 123' >> index.txt"
                sh "scp -v -o StrictHostKeyChecking=no index.txt expertp@172.17.182.9:/home/expertp"
            }
        }
    }
}